Document: seedkit-viewer
Title: Debian seedkit-viewer Manual
Author: <insert document author here>
Abstract: This manual describes what seedkit-viewer is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/seedkit-viewer/seedkit-viewer.sgml.gz

Format: postscript
Files: /usr/share/doc/seedkit-viewer/seedkit-viewer.ps.gz

Format: text
Files: /usr/share/doc/seedkit-viewer/seedkit-viewer.text.gz

Format: HTML
Index: /usr/share/doc/seedkit-viewer/html/index.html
Files: /usr/share/doc/seedkit-viewer/html/*.html
